name: Build & Test

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Swift project
        run: swift build
      
      - name: Run tests
        run: swift test
